(()=>{
const vehicles={'Small Van':{callout:65,ppm:1.3},LWB:{callout:80,ppm:1.7},XLWB:{callout:85,ppm:1.8},'Luton Curtainsider':{callout:95,ppm:2.15}};
const K={quotes:'kls_quotes_v1',jobs:'kls_jobs_v1',invoices:'kls_invoices_v1',customers:'kls_customers_v1',settings:'kls_settings_v1'};
const get=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state={page:'dashboard',quotes:get(K.quotes),jobs:get(K.jobs),invoices:get(K.invoices),customers:get(K.customers),settings:get(K.settings,{business_name:'KLS SameDay',legal_name:'Kings Logistics Services Ltd',phone:'0330 043 5237',whatsapp:'07361 854157',email:'info@klssameday.co.uk',website:'www.klssameday.co.uk',payment_terms:7,bank_name:'',account_name:'',sort_code:'',account_number:''}),notice:''};
const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(v||0)),date=v=>v?new Date(v).toLocaleDateString('en-GB'):'—',uid=p=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){set(K.quotes,state.quotes);set(K.jobs,state.jobs);set(K.invoices,state.invoices);set(K.customers,state.customers);set(K.settings,state.settings)}
function nav(){return [['dashboard','Dashboard'],['newquote','New Quote'],['quotes','Quotes'],['jobs','Jobs'],['invoices','Invoices'],['customers','Customers'],['settings','Settings']]}
function layout(content){return `<div class="shell"><aside id="side" class="side"><div class="logo"><b>KLS</b><span>SameDay Office</span></div><button class="close" data-action="menu-close">×</button><nav>${nav().map(([k,l])=>`<button class="${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('')}</nav><small>Single-user office system<br>Data saved on this device</small></aside><main><header><button class="hamb" data-action="menu-open">☰</button><div><h1>${nav().find(x=>x[0]===state.page)?.[1]}</h1><p>KLS SameDay business control centre</p></div><button class="primary" data-page="newquote">＋ New Quote</button></header>${state.notice?`<div class="notice">${esc(state.notice)}<button data-action="notice-close">×</button></div>`:''}${content}</main></div>`}
const panel=(title,body,sub='',right='')=>`<section class="panel"><div class="panelhead"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${right}</div>${body}</section>`;
function dashboard(){let now=new Date(),month=state.jobs.filter(j=>{let d=new Date(j.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,j)=>s+Number(j.price||0),0),out=state.invoices.filter(i=>i.status!=='Paid').reduce((s,i)=>s+Number(i.total||0),0);return `<section class="hero"><div><small>FAST QUOTING</small><h2>Quote it. Book it. Invoice it.</h2><p>One simple system for your same-day courier work.</p></div><button data-page="newquote">＋ NEW QUOTE</button></section><section class="cards">${card('Pending quotes',state.quotes.filter(q=>q.status==='Pending').length)}${card('Active jobs',state.jobs.filter(j=>j.status!=='Delivered').length)}${card('This month',money(month))}${card('Outstanding',money(out))}</section>${panel('Latest jobs',jobTable(state.jobs.slice(0,6)))}`}
const card=(t,v)=>`<div class="card"><span>◆</span><div><small>${t}</small><b>${v}</b></div></div>`;
function newQuote(){return panel('Create a new quote',`<form id="quote-form"><div class="grid"><label>Customer / company *<input name="customer_name" required></label><label>Telephone<input name="phone"></label><label>Email<input name="email" type="email"></label></div><div class="grid two"><label>Collection address *<textarea name="collection_address" required></textarea></label><label>Delivery address *<textarea name="delivery_address" required></textarea></label></div><div class="grid"><label>Vehicle<select name="vehicle">${Object.keys(vehicles).map(v=>`<option>${v}</option>`).join('')}</select></label><label>Distance (miles)<input name="distance_miles" type="number" min="0" step="0.1"></label><label>Your quoted price<input name="quoted_price" type="number" min="0" step="0.01"><em id="suggestion">Suggested: £95.00</em></label></div><label>Goods description<input name="goods_description"></label><label>Notes<textarea name="notes"></textarea></label><div class="actions"><button type="reset" class="secondary">Clear</button><button class="primary">Save Quote</button></div></form>`,'Give a price first. Convert it to a job when accepted.')}
function quotes(){return panel('Quotes',table(['Quote','Customer','Route','Vehicle','Price','Status','Actions'],state.quotes.map(q=>[q.quote_number,q.customer_name,`${esc(q.collection_address)}<br><i>→ ${esc(q.delivery_address)}</i>`,q.vehicle,money(q.quoted_price),q.status,`<button data-print-quote="${q.id}">Print</button>${q.status==='Pending'?`<button data-accept="${q.id}">Accept → Job</button>`:''}`])))}
function jobs(){return panel('Jobs',jobTable(state.jobs),'',`<label class="search">Search <input id="job-search"></label>`)}
function invoices(){return panel('Invoices',table(['Invoice','Customer','Issue','Due','Total','Status','Actions'],state.invoices.map(i=>[i.invoice_number,i.customer_name,date(i.issue_date),date(i.due_date),money(i.total),`<select data-invoice-status="${i.id}"><option ${i.status==='Unpaid'?'selected':''}>Unpaid</option><option ${i.status==='Paid'?'selected':''}>Paid</option><option ${i.status==='Overdue'?'selected':''}>Overdue</option></select>`,`<button data-print-invoice="${i.id}">Print</button>`])))}
function customers(){return panel('Customers',`<div class="customergrid">${state.customers.length?state.customers.map(c=>`<article><div class="avatar">${esc(c.company_name.slice(0,2).toUpperCase())}</div><div><b>${esc(c.company_name)}</b><p>${esc(c.phone||'No phone')}</p><p>${esc(c.email||'No email')}</p></div></article>`).join(''):'<div class="empty">No customers yet.</div>'}</div>`)}
function settings(){let fields={business_name:'Trading name',legal_name:'Legal name',phone:'Phone',whatsapp:'WhatsApp',email:'Email',website:'Website',bank_name:'Bank',account_name:'Account name',sort_code:'Sort code',account_number:'Account number',payment_terms:'Payment terms (days)'};return panel('Business settings',`<form id="settings-form"><div class="grid two">${Object.entries(fields).map(([k,l])=>`<label>${l}<input name="${k}" value="${esc(state.settings[k])}" ${k==='payment_terms'?'type="number"':''}></label>`).join('')}</div><div class="actions"><button class="primary">Save Settings</button></div></form><p class="saved">✓ Settings are stored on this device.</p>`)}
function table(head,rows){return `<div class="tablewrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}" class="empty">Nothing here yet.</td></tr>`}</tbody></table></div>`}
function jobTable(rows){return table(['Job','Customer','Route','Vehicle','Price','Status','Actions'],rows.map(j=>[j.job_number,j.customer_name,`${esc(j.collection_address)}<br><i>→ ${esc(j.delivery_address)}</i>`,j.vehicle,money(j.price),`<select data-job-status="${j.id}">${['Booked','Collected','In Transit','Delivered','Cancelled'].map(s=>`<option ${j.status===s?'selected':''}>${s}</option>`).join('')}</select>`,`<button data-invoice="${j.id}" ${j.status!=='Delivered'?'disabled':''}>Create Invoice</button>`]))}
function render(){let body=state.page==='dashboard'?dashboard():state.page==='newquote'?newQuote():state.page==='quotes'?quotes():state.page==='jobs'?jobs():state.page==='invoices'?invoices():state.page==='customers'?customers():settings();document.getElementById('app').innerHTML=layout(body);bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelector('[data-action="menu-open"]')?.addEventListener('click',()=>document.getElementById('side').classList.add('open'));document.querySelector('[data-action="menu-close"]')?.addEventListener('click',()=>document.getElementById('side').classList.remove('open'));document.querySelector('[data-action="notice-close"]')?.addEventListener('click',()=>{state.notice='';render()});
let f=document.getElementById('quote-form');if(f){let calc=()=>{let m=Number(f.distance_miles.value||0),r=vehicles[f.vehicle.value],v=m<=10?r.callout:r.callout+(m-10)*r.ppm;document.getElementById('suggestion').textContent='Suggested: '+money(v);if(!f.quoted_price.value)f.quoted_price.value=v.toFixed(2)};f.vehicle.onchange=()=>{f.quoted_price.value='';calc()};f.distance_miles.oninput=()=>{f.quoted_price.value='';calc()};calc();f.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f)),r=vehicles[d.vehicle],m=Number(d.distance_miles||0),suggest=m<=10?r.callout:r.callout+(m-10)*r.ppm,id=uid('cus'),found=state.customers.find(c=>c.company_name.toLowerCase()===d.customer_name.toLowerCase());if(!found)state.customers.unshift({id,company_name:d.customer_name,phone:d.phone,email:d.email,created_at:new Date().toISOString()});let q={...d,id:uid('quo'),customer_id:found?.id||id,quote_number:'Q-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5),quoted_price:Number(d.quoted_price||suggest),status:'Pending',created_at:new Date().toISOString()};state.quotes.unshift(q);state.notice=q.quote_number+' saved.';state.page='quotes';persist();render()}}
document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{let q=state.quotes.find(x=>x.id===b.dataset.accept),j={...q,id:uid('job'),job_number:'KLS-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5),quote_id:q.id,price:q.quoted_price,status:'Booked',created_at:new Date().toISOString()};state.jobs.unshift(j);q.status='Accepted';state.notice=j.job_number+' created.';state.page='jobs';persist();render()});document.querySelectorAll('[data-job-status]').forEach(s=>s.onchange=()=>{state.jobs.find(j=>j.id===s.dataset.jobStatus).status=s.value;persist();render()});document.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>{let j=state.jobs.find(x=>x.id===b.dataset.invoice);if(state.invoices.some(i=>i.job_id===j.id)){state.notice='An invoice already exists for this job.';render();return}let i={id:uid('inv'),invoice_number:'INV-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5),job_id:j.id,customer_name:j.customer_name,total:Number(j.price),status:'Unpaid',issue_date:new Date().toISOString(),due_date:new Date(Date.now()+Number(state.settings.payment_terms||7)*86400000).toISOString()};state.invoices.unshift(i);state.notice=i.invoice_number+' created.';state.page='invoices';persist();render()});document.querySelectorAll('[data-invoice-status]').forEach(s=>s.onchange=()=>{state.invoices.find(i=>i.id===s.dataset.invoiceStatus).status=s.value;persist()});document.querySelectorAll('[data-print-quote]').forEach(b=>b.onclick=()=>printDoc('quote',state.quotes.find(q=>q.id===b.dataset.printQuote)));document.querySelectorAll('[data-print-invoice]').forEach(b=>b.onclick=()=>printDoc('invoice',state.invoices.find(i=>i.id===b.dataset.printInvoice)));let sf=document.getElementById('settings-form');if(sf)sf.onsubmit=e=>{e.preventDefault();state.settings={...state.settings,...Object.fromEntries(new FormData(sf))};state.notice='Settings saved.';persist();render()};let js=document.getElementById('job-search');if(js)js.oninput=()=>{let term=js.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(term)?'':'none')}}
function printDoc(type,row){let isQ=type==='quote',number=isQ?row.quote_number:row.invoice_number,total=isQ?row.quoted_price:row.total,j=!isQ?state.jobs.find(x=>x.id===row.job_id):null,w=open('','_blank');w.document.write(`<html><head><title>${number}</title><style>body{font-family:Arial;padding:40px;color:#111}header{border-bottom:3px solid #111;margin-bottom:25px}h1{margin-bottom:5px}.total{text-align:right;font-size:26px;font-weight:bold;margin-top:35px}</style></head><body><header><h1>${esc(state.settings.business_name)}</h1><p>${esc(state.settings.legal_name)}<br>${esc(state.settings.email)} · ${esc(state.settings.phone)}</p></header><h2>${isQ?'QUOTATION':'INVOICE'} ${number}</h2><p><b>Customer:</b> ${esc(row.customer_name)}</p>${isQ?`<p><b>Collection:</b> ${esc(row.collection_address)}</p><p><b>Delivery:</b> ${esc(row.delivery_address)}</p><p><b>Vehicle:</b> ${esc(row.vehicle)}</p>`:`<p><b>Job:</b> ${esc(j?.job_number||'')}</p><p><b>Issue:</b> ${date(row.issue_date)}</p><p><b>Due:</b> ${date(row.due_date)}</p>`}<div class="total">Total: ${money(total)}</div><p>Payment terms: ${esc(state.settings.payment_terms)} days</p></body></html>`);w.document.close();w.print()}
render();
})();
