import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { supabase, configured } from './supabase'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  LayoutDashboard, Users, Truck, FileText, ReceiptText, Settings,
  Plus, LogOut, Save, Download, Pencil, Trash2, Search, ChevronRight,
  MapPin, Phone, Mail, CheckCircle2, Clock3, PoundSterling, X
} from 'lucide-react'
import './styles.css'

const vehicles = ['Small Van', 'LWB Van', 'XLWB Van', 'Luton Curtainsider with Tail Lift']
const jobStatuses = ['Enquiry', 'Quoted', 'Booked', 'Collected', 'In Transit', 'Delivered', 'Invoiced', 'Paid', 'Cancelled']
const quoteStatuses = ['Draft', 'Sent', 'Accepted', 'Declined', 'Expired']
const invoiceStatuses = ['Not Invoiced', 'Sent', 'Part Paid', 'Paid', 'Overdue']
const rates = {
  'Small Van': { callout: 65, ppm: 1.30 },
  'LWB Van': { callout: 80, ppm: 1.70 },
  'XLWB Van': { callout: 85, ppm: 1.80 },
  'Luton Curtainsider with Tail Lift': { callout: 95, ppm: 2.15 }
}
const blankJob = {customer_id:'',contact_name:'',customer_email:'',customer_phone:'',collection_date:new Date().toISOString().slice(0,10),collection_time:'',collection_address:'',delivery_address:'',vehicle:vehicles[3],goods_description:'',miles:0,base_price:0,extras:0,costs:0,job_status:'Booked',quote_status:'Accepted',invoice_status:'Not Invoiced',invoice_date:'',amount_paid:0,paid_date:'',pod_notes:''}
const defaultSettings = {trading_name:'KLS SameDay',legal_name:'Kings Logistics Services Ltd',phone:'0330 043 5237',whatsapp:'07361 854157',email:'info@klssameday.co.uk',website:'klssameday.co.uk',address_line:'Based in Essex — Nationwide Coverage',bank_name:'',sort_code:'',account_number:'',default_terms:7}
const money = n => new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n||0))
const fmtDate = d => d ? new Date(`${d}T12:00:00`).toLocaleDateString('en-GB') : '—'

function App(){
  const [session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard')
  const [customers,setCustomers]=useState([]),[jobs,setJobs]=useState([]),[settings,setSettings]=useState(defaultSettings)
  const [newJobOpen,setNewJobOpen]=useState(false)
  useEffect(()=>{if(!configured){setReady(true);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)}); const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
  useEffect(()=>{if(session)loadAll()},[session])
  async function loadAll(){
    const [{data:c,error:ce},{data:j,error:je},{data:s}] = await Promise.all([
      supabase.from('customers').select('*').order('company'),
      supabase.from('jobs').select('*').order('created_at',{ascending:false}),
      supabase.from('business_settings').select('*').limit(1).maybeSingle()
    ])
    if(!ce)setCustomers(c||[]); if(!je)setJobs(j||[]); if(s)setSettings(s)
  }
  if(!ready)return <div className="centre">Loading KLS SameDay Office…</div>
  if(!configured)return <SetupScreen/>
  if(!session)return <Login/>
  return <div className="shell">
    <aside><div className="brand"><strong>KLS</strong><span>SameDay Office</span></div><Nav page={page} setPage={setPage}/><button className="signout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/> Sign out</button></aside>
    <main>
      <header className="topbar"><div><span className="eyebrow">KLS SAMEDAY</span><h1>{page[0].toUpperCase()+page.slice(1)}</h1></div><button className="top-new" onClick={()=>setNewJobOpen(true)}><Plus size={20}/> New job</button></header>
      {page==='dashboard'&&<Dashboard jobs={jobs} customers={customers} openNew={()=>setNewJobOpen(true)} setPage={setPage}/>} 
      {page==='customers'&&<Customers customers={customers} jobs={jobs} reload={loadAll}/>} 
      {page==='jobs'&&<Jobs jobs={jobs} customers={customers} reload={loadAll} openNew={()=>setNewJobOpen(true)}/>} 
      {page==='quotes'&&<Documents mode="quote" jobs={jobs} customers={customers} settings={settings}/>} 
      {page==='invoices'&&<Documents mode="invoice" jobs={jobs} customers={customers} settings={settings}/>} 
      {page==='settings'&&<SettingsPage settings={settings} setSettings={setSettings}/>} 
    </main>
    {newJobOpen&&<NewJobModal customers={customers} reload={loadAll} close={()=>setNewJobOpen(false)}/>} 
  </div>
}

function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[mode,setMode]=useState('login');async function submit(e){e.preventDefault();setMessage('');const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setMessage(result.error.message);else if(mode==='signup')setMessage('Account created. Check your email if confirmation is enabled, then sign in.')}return <div className="login-wrap"><form className="login-card" onSubmit={submit}><div className="login-logo">KLS</div><h1>SameDay Office</h1><p>{mode==='login'?'Secure business login':'Create your secure office account'}</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className={message.startsWith('Account')?'success':'error'}>{message}</div>}<button className="primary wide">{mode==='login'?'Sign in':'Create account'}</button><button type="button" className="text-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'First time here? Create account':'Already have an account? Sign in'}</button></form></div>}
function SetupScreen(){return <div className="centre setup"><h1>KLS SameDay Office</h1><p>Add your Supabase details to Vercel Environment Variables, then redeploy.</p></div>}
function Nav({page,setPage}){const items=[['dashboard','Dashboard',LayoutDashboard],['customers','Customers',Users],['jobs','Jobs',Truck],['quotes','Quotes',FileText],['invoices','Invoices',ReceiptText],['settings','Settings',Settings]];return <nav>{items.map(([id,l,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={18}/>{l}</button>)}</nav>}

function Dashboard({jobs,customers,openNew,setPage}){
  const today=new Date().toISOString().slice(0,10), month=today.slice(0,7)
  const todayJobs=jobs.filter(j=>j.collection_date===today)
  const total=jobs.reduce((a,j)=>a+Number(j.total_price||0),0),paid=jobs.reduce((a,j)=>a+Number(j.amount_paid||0),0)
  const monthly=jobs.filter(j=>(j.collection_date||'').startsWith(month)).reduce((a,j)=>a+Number(j.total_price||0),0)
  const unpaid=jobs.filter(j=>Number(j.total_price||0)>Number(j.amount_paid||0)&&j.job_status!=='Cancelled')
  return <>
    <button className="new-job-hero" onClick={openNew}><div><span>FAST BOOKING</span><strong><Plus size={30}/> NEW JOB</strong><small>Customer, collection, delivery, vehicle and price — all on one screen</small></div><ChevronRight size={34}/></button>
    <div className="cards">
      <Metric icon={Truck} label="Today's jobs" value={todayJobs.length}/><Metric icon={PoundSterling} label="This month" value={money(monthly)}/><Metric icon={Clock3} label="Outstanding" value={money(total-paid)}/><Metric icon={Users} label="Customers" value={customers.length}/>
    </div>
    <div className="dashboard-grid"><section className="panel"><div className="section-head"><div><h2>Today’s jobs</h2><p>{fmtDate(today)}</p></div><button className="link-button" onClick={()=>setPage('jobs')}>View all</button></div>{todayJobs.length?<JobCards jobs={todayJobs} customers={customers}/>:<Empty text="No jobs booked for today." action="Book a job" onClick={openNew}/>}</section>
    <section className="panel"><div className="section-head"><div><h2>Money to collect</h2><p>{unpaid.length} unpaid job{unpaid.length===1?'':'s'}</p></div></div>{unpaid.slice(0,6).map(j=><div className="money-row" key={j.id}><div><strong>{j.job_number}</strong><span>{customerName(j,customers)}</span></div><b>{money(Number(j.total_price||0)-Number(j.amount_paid||0))}</b></div>)}{!unpaid.length&&<Empty text="Everything is paid."/>}</section></div>
    <section className="panel"><div className="section-head"><div><h2>Recent work</h2><p>Latest jobs and progress</p></div></div><JobTable jobs={jobs.slice(0,8)} customers={customers} compact/></section>
  </>
}
function Metric({icon:Icon,label,value}){return <div className="card metric"><div className="metric-icon"><Icon size={21}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Empty({text,action,onClick}){return <div className="empty"><CheckCircle2 size={34}/><p>{text}</p>{action&&<button className="secondary" onClick={onClick}>{action}</button>}</div>}

function NewJobModal({customers,reload,close,existing=null}){
  const [form,setForm]=useState(existing?{...blankJob,...existing}:blankJob),[saving,setSaving]=useState(false),[error,setError]=useState('')
  function change(k,v){setForm(f=>({...f,[k]:v}))}
  function chooseCustomer(id){const c=customers.find(x=>x.id===id);setForm(f=>({...f,customer_id:id,contact_name:c?.contact_name||'',customer_email:c?.email||'',customer_phone:c?.phone||''}))}
  function suggest(){const r=rates[form.vehicle],m=Number(form.miles||0),p=m<=10?r.callout:r.callout+(m-10)*r.ppm;change('base_price',Math.ceil(p/5)*5)}
  async function save(e){e.preventDefault();setSaving(true);setError('');let customerId=form.customer_id
    if(!customerId&&form.contact_name){const company=form.contact_name.trim();const {data,error}=await supabase.from('customers').insert({company,contact_name:form.contact_name,phone:form.customer_phone,email:form.customer_email,payment_terms:7}).select().single();if(error){setError(error.message);setSaving(false);return}customerId=data.id}
    const payload={...form,customer_id:customerId,total_price:Number(form.base_price||0)+Number(form.extras||0)};delete payload.customer_phone
    const result=existing?await supabase.from('jobs').update(payload).eq('id',existing.id):await supabase.from('jobs').insert(payload)
    setSaving(false);if(result.error){setError(result.error.message);return}await reload();close()}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><span className="eyebrow">FAST BOOKING</span><h2>{existing?'Edit job':'New job'}</h2></div><button className="close" onClick={close}><X/></button></div><form onSubmit={save} className="form-grid quick-form">
    <SelectField label="Existing customer" value={form.customer_id} options={customers.map(c=>[c.id,c.company])} placeholder="New customer / cash customer" onChange={chooseCustomer}/>
    <Field label="Customer / company name" value={form.contact_name} onChange={v=>change('contact_name',v)} required/>
    <Field label="Telephone" value={form.customer_phone||''} onChange={v=>change('customer_phone',v)}/><Field label="Email" type="email" value={form.customer_email||''} onChange={v=>change('customer_email',v)}/>
    <Field label="Collection address / postcode" textarea value={form.collection_address} onChange={v=>change('collection_address',v)} required/>
    <Field label="Delivery address / postcode" textarea value={form.delivery_address} onChange={v=>change('delivery_address',v)} required/>
    <Field label="Collection date" type="date" value={form.collection_date} onChange={v=>change('collection_date',v)} required/><Field label="Collection time" type="time" value={form.collection_time} onChange={v=>change('collection_time',v)}/>
    <SelectField label="Vehicle" value={form.vehicle} options={vehicles} onChange={v=>change('vehicle',v)}/><Field label="Goods / job description" value={form.goods_description} onChange={v=>change('goods_description',v)}/>
    <Field label="Chargeable miles" type="number" step="0.1" value={form.miles} onChange={v=>change('miles',+v)}/><div className="field"><span>Suggested / agreed price</span><div className="price-row"><input type="number" step="0.01" value={form.base_price} onChange={e=>change('base_price',+e.target.value)}/><button type="button" className="secondary" onClick={suggest}>Suggest</button></div></div>
    <Field label="Extras (£)" type="number" step="0.01" value={form.extras} onChange={v=>change('extras',+v)}/><SelectField label="Job status" value={form.job_status} options={jobStatuses} onChange={v=>change('job_status',v)}/>
    {error&&<div className="error full">{error}</div>}<div className="quick-total full"><span>Total customer price</span><strong>{money(Number(form.base_price||0)+Number(form.extras||0))}</strong></div><div className="full modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={saving}><Save size={18}/>{saving?'Saving…':'Save job'}</button></div>
  </form></div></div>
}

function Customers({customers,jobs,reload}){const[search,setSearch]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState({company:'',contact_name:'',phone:'',email:'',billing_address:'',payment_terms:7,notes:''});const filtered=customers.filter(c=>`${c.company} ${c.contact_name} ${c.phone} ${c.email}`.toLowerCase().includes(search.toLowerCase()));async function save(e){e.preventDefault();await supabase.from('customers').insert(form);setShow(false);setForm({company:'',contact_name:'',phone:'',email:'',billing_address:'',payment_terms:7,notes:''});reload()}async function remove(id){if(confirm('Delete this customer?')){await supabase.from('customers').delete().eq('id',id);reload()}}return <><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search company, contact, phone or email" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="primary" onClick={()=>setShow(!show)}><Plus size={18}/> Add customer</button></div>{show&&<section className="panel"><h2>Add customer</h2><form onSubmit={save} className="form-grid"><Field label="Company" value={form.company} onChange={v=>setForm({...form,company:v})} required/><Field label="Contact name" value={form.contact_name} onChange={v=>setForm({...form,contact_name:v})}/><Field label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="Email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Billing address" textarea value={form.billing_address} onChange={v=>setForm({...form,billing_address:v})}/><Field label="Payment terms" type="number" value={form.payment_terms} onChange={v=>setForm({...form,payment_terms:+v})}/><Field label="Notes" textarea value={form.notes} onChange={v=>setForm({...form,notes:v})}/><div className="full"><button className="primary"><Save size={17}/> Save customer</button></div></form></section>}<div className="customer-grid">{filtered.map(c=>{const cj=jobs.filter(j=>j.customer_id===c.id);const outstanding=cj.reduce((a,j)=>a+Number(j.total_price||0)-Number(j.amount_paid||0),0);return <article className="customer-card" key={c.id}><div className="customer-top"><div className="avatar">{c.company?.[0]||'K'}</div><div><h3>{c.company}</h3><span>{c.contact_name||'No contact name'}</span></div><button className="icon danger" onClick={()=>remove(c.id)}><Trash2 size={16}/></button></div><div className="contact-lines">{c.phone&&<span><Phone size={15}/>{c.phone}</span>}{c.email&&<span><Mail size={15}/>{c.email}</span>}</div><div className="customer-stats"><div><span>Jobs</span><strong>{cj.length}</strong></div><div><span>Outstanding</span><strong>{money(outstanding)}</strong></div><div><span>Terms</span><strong>{c.payment_terms} days</strong></div></div></article>})}</div></>}

function Jobs({jobs,customers,reload,openNew}){const[search,setSearch]=useState(''),[status,setStatus]=useState('All'),[editing,setEditing]=useState(null);const filtered=jobs.filter(j=>(status==='All'||j.job_status===status)&&`${j.job_number} ${customerName(j,customers)} ${j.collection_address} ${j.delivery_address}`.toLowerCase().includes(search.toLowerCase()));async function remove(id){if(confirm('Delete this job?')){await supabase.from('jobs').delete().eq('id',id);reload()}}async function quickStatus(j,s){await supabase.from('jobs').update({job_status:s,invoice_status:s==='Invoiced'?'Sent':j.invoice_status}).eq('id',j.id);reload()}return <><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search job number, customer or address" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="status-filter" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{jobStatuses.map(s=><option key={s}>{s}</option>)}</select><button className="primary" onClick={openNew}><Plus size={18}/> New job</button></div><section className="panel"><JobTable jobs={filtered} customers={customers} edit={setEditing} remove={remove} quickStatus={quickStatus}/></section>{editing&&<NewJobModal existing={editing} customers={customers} reload={reload} close={()=>setEditing(null)}/>}</>}
function JobCards({jobs,customers}){return <div className="job-cards">{jobs.map(j=><article className="job-card" key={j.id}><div className="job-time">{j.collection_time?.slice(0,5)||'Any time'}</div><div className="job-route"><strong>{customerName(j,customers)}</strong><span><MapPin size={14}/>{j.collection_address||'Collection not entered'}</span><span><MapPin size={14}/>{j.delivery_address||'Delivery not entered'}</span></div><div><span className={`badge ${slug(j.job_status)}`}>{j.job_status}</span><b>{money(j.total_price)}</b></div></article>)}</div>}
function JobTable({jobs,customers=[],edit,remove,quickStatus,compact=false}){return <div className="table-wrap"><table><thead><tr><th>Job</th><th>Customer</th><th>Date</th><th>Route</th><th>Vehicle</th><th>Total</th><th>Status</th>{!compact&&<th>Actions</th>}</tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.job_number||'Pending'}</strong></td><td>{customerName(j,customers)}</td><td>{fmtDate(j.collection_date)}<br/><small>{j.collection_time?.slice(0,5)}</small></td><td className="route-cell"><span>{j.collection_address||'—'}</span><span>→ {j.delivery_address||'—'}</span></td><td>{j.vehicle}</td><td><strong>{money(j.total_price)}</strong></td><td><span className={`badge ${slug(j.job_status)}`}>{j.job_status}</span></td>{!compact&&<td><div className="row-actions"><select value={j.job_status} onChange={e=>quickStatus(j,e.target.value)}>{jobStatuses.map(s=><option key={s}>{s}</option>)}</select><button className="icon" onClick={()=>edit(j)}><Pencil size={16}/></button><button className="icon danger" onClick={()=>remove(j.id)}><Trash2 size={16}/></button></div></td>}</tr>)}</tbody></table>{!jobs.length&&<Empty text="No matching jobs."/>}</div>}

function Documents({mode,jobs,customers,settings}){const[id,setId]=useState(''),job=jobs.find(j=>j.id===id);function pdf(){if(!job)return;const c=customers.find(x=>x.id===job.customer_id),doc=new jsPDF(),type=mode==='quote'?'QUOTATION':'INVOICE';doc.setFontSize(24);doc.text(settings.trading_name||'KLS SameDay',15,20);doc.setFontSize(10);doc.text(settings.address_line||'',15,27);doc.text(settings.email||'',15,33);doc.setFontSize(20);doc.text(type,150,20);doc.setFontSize(10);doc.text(`${mode==='quote'?'Quote':'Invoice'} ref: ${job.job_number}`,150,28);doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`,150,34);doc.setFontSize(12);doc.text(`Customer: ${c?.company||job.contact_name||'Customer'}`,15,52);if(c?.billing_address)doc.text(c.billing_address,15,59,{maxWidth:80});autoTable(doc,{startY:78,head:[['Collection','Delivery','Vehicle','Description','Price']],body:[[job.collection_address,job.delivery_address,job.vehicle,job.goods_description,money(job.total_price)]],styles:{fontSize:8},headStyles:{fillColor:[20,20,20]}});doc.setFontSize(15);doc.text(`TOTAL: ${money(job.total_price)}`,145,doc.lastAutoTable.finalY+18);if(mode==='invoice'){doc.setFontSize(9);doc.text(`Payment terms: ${c?.payment_terms||settings.default_terms||7} days`,15,doc.lastAutoTable.finalY+35);doc.text(`Bank: ${settings.bank_name||'Add bank details in Settings'}`,15,doc.lastAutoTable.finalY+42);doc.text(`Sort code: ${settings.sort_code||'—'}   Account: ${settings.account_number||'—'}`,15,doc.lastAutoTable.finalY+49)}doc.save(`${type}-${job.job_number}.pdf`)}return <><section className="panel"><div className="section-head"><div><h2>Create {mode}</h2><p>Select a job, preview the details and download the PDF.</p></div></div><div className="document-picker"><label>Job<select value={id} onChange={e=>setId(e.target.value)}><option value="">Choose a job…</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.job_number} — {customerName(j,customers)} — {money(j.total_price)}</option>)}</select></label><button className="primary" disabled={!job} onClick={pdf}><Download size={18}/> Download PDF</button></div></section>{job&&<section className="paper"><div className="paper-head"><div><h1>{settings.trading_name}</h1><p>{settings.address_line}</p></div><div><h2>{mode==='quote'?'QUOTATION':'INVOICE'}</h2><p>{job.job_number}</p></div></div><div className="details"><strong>{customerName(job,customers)}</strong><p>{job.collection_address}</p><p>to</p><p>{job.delivery_address}</p></div><div className="doc-total">Total: {money(job.total_price)}</div></section>}</>}
function SettingsPage({settings,setSettings}){const[form,setForm]=useState(settings),[saved,setSaved]=useState(false);useEffect(()=>setForm(settings),[settings]);async function save(e){e.preventDefault();const{data:existing}=await supabase.from('business_settings').select('id').limit(1).maybeSingle();const result=existing?await supabase.from('business_settings').update(form).eq('id',existing.id):await supabase.from('business_settings').insert(form);if(!result.error){setSettings(form);setSaved(true);setTimeout(()=>setSaved(false),2500)}}return <section className="panel"><h2>Business details</h2><p>These details appear on your quotes and invoices.</p><form onSubmit={save} className="form-grid"><Field label="Trading name" value={form.trading_name||''} onChange={v=>setForm({...form,trading_name:v})}/><Field label="Legal name" value={form.legal_name||''} onChange={v=>setForm({...form,legal_name:v})}/><Field label="Phone" value={form.phone||''} onChange={v=>setForm({...form,phone:v})}/><Field label="WhatsApp" value={form.whatsapp||''} onChange={v=>setForm({...form,whatsapp:v})}/><Field label="Email" value={form.email||''} onChange={v=>setForm({...form,email:v})}/><Field label="Website" value={form.website||''} onChange={v=>setForm({...form,website:v})}/><Field label="Business line" value={form.address_line||''} onChange={v=>setForm({...form,address_line:v})}/><Field label="Payment terms" type="number" value={form.default_terms||7} onChange={v=>setForm({...form,default_terms:+v})}/><Field label="Bank name" value={form.bank_name||''} onChange={v=>setForm({...form,bank_name:v})}/><Field label="Sort code" value={form.sort_code||''} onChange={v=>setForm({...form,sort_code:v})}/><Field label="Account number" value={form.account_number||''} onChange={v=>setForm({...form,account_number:v})}/><div className="full"><button className="primary"><Save size={17}/> Save settings</button>{saved&&<span className="saved">Saved</span>}</div></form></section>}

function Field({label,textarea=false,onChange,...props}){return <label>{label}{textarea?<textarea {...props} onChange={e=>onChange(e.target.value)}/>:<input {...props} onChange={e=>onChange(e.target.value)}/>}</label>}
function SelectField({label,value,options,onChange,placeholder}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{placeholder&&<option value="">{placeholder}</option>}{options.map(o=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>)}</select></label>}
function customerName(j,customers){return customers.find(c=>c.id===j.customer_id)?.company||j.contact_name||'Cash customer'}
function slug(s){return String(s||'').toLowerCase().replaceAll(' ','-')}

createRoot(document.getElementById('root')).render(<App/>)
